const Actions = {
  LOADING: "LOADING",
  GET_TRENDING: "GET_TRENDING",
  GET_RANDOM: "GET_RANDOM",
  GET_SEARCH: "GET_SEARCH",
  ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
  GET_FAVOURITES: "GET_FAVOURITES",
};

export default Actions;
